### ISSUE TITLE
iPXE not working

### ISSUE THREAD

**Issue by olafura** [fhunleth/vultr_example#1]
Apparently the `#!ipxe` is missing but even with that it's not working I will try tomorrow with a new fw. I haven't even had success with qemu. I always get the login screen and nothing else.

But thank you for those instructions I've been wanting to do this for a long time since it really cool and possible promising way of having a super fast and possible more secure cloud instance ;)

**Comment by olafura** [comment]
![screenshot from 2017-09-14 19-29-00](https://user-images.githubusercontent.com/292662/30460153-090eced2-9983-11e7-8c5f-ae5cb11c0b14.png)

**Comment by fhunleth** [comment]
I'll remove the `/root/authorized_keys` part. That was from a previous try where I was trying to do some deployment in the loader. I stopped doing that so it's a bogus error now.

Can you add 
```
initrd https://s3.amazonaws.com/files.troodon-software.com/vultr/authorized_key /root/authorized_keys
```
 to your .ipxe file in the mean time? It's ignored, so it doesn't matter that it's my key.

**Comment by fhunleth** [comment]
Ok, I just updated the loader to skip the `authorized_keys` part that was give the error above. Everything is reachable from my S3 URLs. There's something weird at the moment with the ipxe script. I think that it's being cached on Vultr for me. Maybe this won't happen for you. If it does, just run `boot` at the prompt. That was the only missing step for me. Otherwise, it is working for me. I bootstrapped and deployed a server just now to verify.

For reference, here's the path the the ipxe script that I used to test:

https://s3.amazonaws.com/files.troodon-software.com/vultr/nerves_vultr_loader.ipxe

**Comment by fhunleth** [comment]
One more thing: You mentioned QEMU, but I've never tried any of this with it. The nice part about QEMU is that you don't need the loader or the iPXE script since a `mix firmware.image` on your project can almost initialize the storage. It will make a file that's a too small and there will be an error when formatting the application writable partition (all of this is fixable). Unless you use that writable partition, you'll be ok. However, since I haven't tried or written up the QEMU route, I'd just stick to Vultr for now if you can.

**Comment by olafura** [comment]
I'll check later since Vultr seems to have problems with login :D

**Comment by olafura** [comment]
That did the trick ;)

**Comment by fhunleth** [comment]
:+1:
